# Generated by pg_lens's release workflow (scripts/gen_cask.sh) — do not edit by hand.
cask "pg_lens" do
  version "0.7.0"

  arch arm: "aarch64", intel: "x86_64"

  sha256 arm:   "05340064d41942225476ee537b891d20d5076be6c2e7119513aadebef5bf4359",
         intel: "9e3173bf2917db381cf56023a76097a1d19c0190f653ecf1f5eec2b928800719"

  url "https://github.com/dog-hero/pg_lens/releases/download/v#{version}/pg_lens-v#{version}-#{arch}-apple-darwin.tar.gz"
  name "pg_lens"
  desc "Live PostgreSQL observability: TUI and web dashboard in one binary"
  homepage "https://github.com/dog-hero/pg_lens"

  binary "pg_lens-v#{version}-#{arch}-apple-darwin/pg_lens"

  # The binary is not yet notarized with an Apple Developer ID, so Gatekeeper
  # would kill it. Homebrew removed the `--no-quarantine` flag, so the cask
  # clears the quarantine attribute itself on install.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine",
                          "#{staged_path}/pg_lens-v#{version}-#{arch}-apple-darwin/pg_lens"]
  end

  caveats <<~EOS
    pg_lens is not yet notarized. If macOS still refuses to run it, clear the
    quarantine flag once:
      xattr -d com.apple.quarantine "/bin/pg_lens"
  EOS
end
