# Generated by pg_lens's release workflow (scripts/gen_cask.sh) — do not edit by hand.
cask "pg_lens" do
  version "0.5.1"

  arch arm: "aarch64", intel: "x86_64"

  sha256 arm:   "2747abc01223ac9ef1872626b34d8bc03dbd5e0cd328a0edcc00e1878d03b4d7",
         intel: "09f79e04e4e06556ab503b0e45d375caf0ad84d44671576f118696877880c0c1"

  url "https://github.com/dog-hero/pg_lens/releases/download/v#{version}/pg_lens-v#{version}-#{arch}-apple-darwin.tar.gz"
  name "pg_lens"
  desc "Live PostgreSQL observability: TUI and web dashboard in one binary"
  homepage "https://github.com/dog-hero/pg_lens"

  binary "pg_lens-v#{version}-#{arch}-apple-darwin/pg_lens"
end
