# Generated by pg_lens's release workflow (scripts/gen_cask.sh) — do not edit by hand.
cask "pg_lens" do
  version "0.4.0"

  arch arm: "aarch64", intel: "x86_64"

  sha256 arm:   "3fa6c9b56e8b4f54c24a005491de0d461799602f0735a56b71f5c3bcfcee5022",
         intel: "375c200c6467a3ed4821e8e5cc6fc412e3d52383eaf0bf2632f3664354c5c336"

  url "https://github.com/dog-hero/pg_lens/releases/download/v#{version}/pg_lens-v#{version}-#{arch}-apple-darwin.tar.gz"
  name "pg_lens"
  desc "Live PostgreSQL observability: TUI and web dashboard in one binary"
  homepage "https://github.com/dog-hero/pg_lens"

  binary "pg_lens-v#{version}-#{arch}-apple-darwin/pg_lens"
end
