# Generated by pg_lens's release workflow (scripts/gen_formula.sh) — do not edit by hand.
class PgLens < Formula
  desc "Live PostgreSQL observability: TUI and web dashboard in one binary"
  homepage "https://github.com/dog-hero/pg_lens"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.11.0/pg_lens-v0.11.0-aarch64-apple-darwin.tar.gz"
      sha256 "49806eb25c9afbf0361377240e6b0328683e54c49bdc6c64b2c676d7b10e983f"
    else
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.11.0/pg_lens-v0.11.0-x86_64-apple-darwin.tar.gz"
      sha256 "de7c583d7ee4f791730d15df96d7289ebe175084683311ca14e8f6e4ca156be3"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.11.0/pg_lens-v0.11.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4c7a16afa9068fdcab58084ae75c551ed035ac34bd36cb506b77b393031c6d6f"
    else
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.11.0/pg_lens-v0.11.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2ac4653dbe1aa29f91cd5ebd4082a1a2655d610d6e6a18db23a634a84a245c02"
    end
  end

  def install
    bin.install "pg_lens"
  end

  test do
    assert_match "pg_lens", shell_output("#{bin}/pg_lens --help")
  end
end
