# Generated by pg_lens's release workflow (scripts/gen_formula.sh) — do not edit by hand.
class PgLens < Formula
  desc "Live PostgreSQL observability: TUI and web dashboard in one binary"
  homepage "https://github.com/dog-hero/pg_lens"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.13.0/pg_lens-v0.13.0-aarch64-apple-darwin.tar.gz"
      sha256 "6e867db77782d340d02828f7670f44cf8cbacd81c9875d87766bbbc58cabcd56"
    else
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.13.0/pg_lens-v0.13.0-x86_64-apple-darwin.tar.gz"
      sha256 "e5af53baac6ed5e65dac077b6dcea2b26deb76bd523bcba970b0e03f0e6b2e62"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.13.0/pg_lens-v0.13.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "001c54384560e10c938826ac92a7c8761ab29cc8bd0a96a379b559a93648d122"
    else
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.13.0/pg_lens-v0.13.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "6d733bde3b8d714c7ab210453aa4a5264d234568253525f407057932dbe8b364"
    end
  end

  def install
    bin.install "pg_lens"
  end

  test do
    assert_match "pg_lens", shell_output("#{bin}/pg_lens --help")
  end
end
