# Generated by pg_lens's release workflow (scripts/gen_formula.sh) — do not edit by hand.
class PgLens < Formula
  desc "Live PostgreSQL observability: TUI and web dashboard in one binary"
  homepage "https://github.com/dog-hero/pg_lens"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.5.2/pg_lens-v0.5.2-aarch64-apple-darwin.tar.gz"
      sha256 "9ac0d571dea99561a1c6754174e404ef3848d9b940b726aa257e5486dd477ef6"
    else
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.5.2/pg_lens-v0.5.2-x86_64-apple-darwin.tar.gz"
      sha256 "8da337b3eadec9645ecc27461a23392dc9fc7bf0d22789e214aeb60bf291c37a"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.5.2/pg_lens-v0.5.2-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c9b12f390e56572aec7d745392ef4fa5a82a2bd44870ed9f7ed00ae890b09468"
    else
      url "https://github.com/dog-hero/pg_lens/releases/download/v0.5.2/pg_lens-v0.5.2-x86_64-unknown-linux-musl.tar.gz"
      sha256 "c13277c7e7fdc389416455614af2339aac175f1501d8e6217bf8d9774947d51a"
    end
  end

  def install
    bin.install "pg_lens"
  end

  test do
    assert_match "pg_lens", shell_output("#{bin}/pg_lens --help")
  end
end
